### ISSUE TITLE
crash while swiping up to add feed

### ISSUE THREAD

**Issue by yash-garg** [msasikanth/twine#27]
**Describe the bug**
App crashes on latest Play Store release when trying to swipe up on the home page.

**To Reproduce**
1. Open the app
2. Swipe up to open the bottom sheet
3. Crash observed

**Device Information**
 - Device: Poco F1
 - OS: Android 12 
 - App Version: v1.1.2-PROD

**Stacktrace**
```java
05-25 11:16:36.609 15639 15639 E AndroidRuntime: java.lang.IllegalArgumentException: Padding must be non-negative
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at u.r0.<init>(Unknown Source:72)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at h7.l.S0(Unknown Source:7)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at h7.l.T0(Unknown Source:21)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at i5.r.a(Unknown Source:943)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at q.s.a(Unknown Source:26)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at q.s.a0(Unknown Source:17)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at i0.y.H(Unknown Source:283)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at q.u1.b(Unknown Source:356)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at q.u1.T(Unknown Source:32)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at a7.h.s0(Unknown Source:42)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at i0.y.o(Unknown Source:128)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at i0.y.G(Unknown Source:35)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at i0.d0.u(Unknown Source:17)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at i0.w1.n(Unknown Source:100)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at u.t.j0(Unknown Source:415)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at androidx.compose.ui.platform.o0.doFrame(Unknown Source:6)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at androidx.compose.ui.platform.m0.doFrame(Unknown Source:47)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-25 11:16:36.609 15639 15639 E AndroidRuntime: 	Suppressed: s7.f: [i0.h1@fbfe505, androidx.compose.ui.platform.m1@35a395a, o1{Cancelling}@80078b, n0@951c068]
05-25 11:16:42.741 15785 15785 E AndroidRuntime: FATAL EXCEPTION: main
05-25 11:16:42.741 15785 15785 E AndroidRuntime: Process: dev.sasikanth.rss.reader, PID: 15785
```

**Comment by msasikanth** [comment]
Thanks for raising the issue. I have made a small change and it should fix the issue. It's available on Play Store, can check once please

**Comment by yash-garg** [comment]
> Thanks for raising the issue. I have made a small change and it should fix the issue. It's available on Play Store, can check once please

Works fine now!
