### ISSUE TITLE
Timeout error or another error when adding RSS feed

### ISSUE THREAD

**Issue by tejuguasu** [msasikanth/twine#335]
**Describe the bug**
Error when trying to add a new feed.
```
REQUEST https://rss.cnn.com/rss/edition.rss failed with exception: io.ktor.client.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://rss.cnn.com/rss/edition.rss, connect_timeout=unknown ms]
```

I hope this is an env setup issue on my side and not a problem with the code.
The Android app from the Play Store works fine, the issue arises when debugging/running from IntelliJ IDEA Ultimate through the emulator.

Most of the time, I just get the `Bugsnag` start issue, hiding the real error. Sometimes I can see the timeout error. Already checked and from the emulator I can access the URL using Chrome.

**To Reproduce**
1. Start the application and expand the lower panel
2. Click on Add feed
3. Add a feed URL (tried with `https://www.rollingstone.com/rss`, `https://rss.cnn.com/rss/edition.rss` and some more)
4. The application crashes

**Screenshots**

**Device Information**
 - Device: Pixel 3
 - OS: The typical emulated Android
 - App Version v1.38.0 (latest at the time of ticket creation)

**Stacktrace**

## Only `HttpClient`
```
2024-02-21 16:43:04.555  4938-4990  HttpClient              dev.sasikanth.rss.reader.debug       I  ---
                                                                                                    REQUEST: https://www.rollingstone.com/rss
                                                                                                    METHOD: HttpMethod(value=GET)
                                                                                                    ---
2024-02-21 16:43:05.370  4938-4968  HttpClient              dev.sasikanth.rss.reader.debug       I  ---
                                                                                                    RESPONSE: 301 
                                                                                                    METHOD: HttpMethod(value=GET)
                                                                                                    FROM: https://www.rollingstone.com/rss
                                                                                                    ---
2024-02-21 16:43:05.376  4938-4990  HttpClient              dev.sasikanth.rss.reader.debug       I  ---
                                                                                                    REQUEST https://www.rollingstone.com/rss failed with exception: java.lang.IllegalStateException: You must call Bugsnag.start before any other Bugsnag methods
                                                                                                    ---
```

## Complete logs
```
2024-02-21 16:42:59.471  4938-4964  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=127.91ms min=12.34ms max=483.09ms count=9
2024-02-21 16:43:00.491  4938-4964  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=509.71ms min=500.25ms max=519.17ms count=2
2024-02-21 16:43:01.992  4938-4964  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=499.79ms min=484.19ms max=511.42ms count=3
2024-02-21 16:43:03.277  4938-4964  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=321.10ms min=12.29ms max=506.97ms count=4
2024-02-21 16:43:04.506  4938-4990  Compatibil...geReporter dev.sasikanth.rss.reader.debug       D  Compat change id reported: 247079863; UID 10193; state: ENABLED
2024-02-21 16:43:04.518  4938-4938  ImeTracker              dev.sasikanth.rss.reader.debug       I  dev.sasikanth.rss.reader.debug:7b67a694: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
2024-02-21 16:43:04.520  4938-4938  ImeTracker              dev.sasikanth.rss.reader.debug       I  dev.sasikanth.rss.reader.debug:8ef608c5: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
2024-02-21 16:43:04.555  4938-4990  HttpClient              dev.sasikanth.rss.reader.debug       I  ---
                                                                                                    REQUEST: https://www.rollingstone.com/rss
                                                                                                    METHOD: HttpMethod(value=GET)
                                                                                                    ---
2024-02-21 16:43:04.576  4938-4964  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=432.79ms min=320.82ms max=491.24ms count=3
2024-02-21 16:43:04.604  4938-4938  ImeTracker              dev.sasikanth.rss.reader.debug       I  dev.sasikanth.rss.reader.debug:8ef608c5: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
2024-02-21 16:43:04.606  4938-4938  WindowOnBackDispatcher  dev.sasikanth.rss.reader.debug       W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@92750332 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@c1cd879
2024-02-21 16:43:04.893  4938-4938  ImeTracker              dev.sasikanth.rss.reader.debug       I  dev.sasikanth.rss.reader.debug:9a469956: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
2024-02-21 16:43:04.895  4938-4938  ImeTracker              dev.sasikanth.rss.reader.debug       I  dev.sasikanth.rss.reader.debug:7b67a694: onHidden
2024-02-21 16:43:05.012  4938-5010  TrafficStats            dev.sasikanth.rss.reader.debug       D  tagSocket(120) with statsTag=0xffffffff, statsUid=-1
2024-02-21 16:43:05.370  4938-4968  HttpClient              dev.sasikanth.rss.reader.debug       I  ---
                                                                                                    RESPONSE: 301 
                                                                                                    METHOD: HttpMethod(value=GET)
                                                                                                    FROM: https://www.rollingstone.com/rss
                                                                                                    ---
2024-02-21 16:43:05.376  4938-4990  HttpClient              dev.sasikanth.rss.reader.debug       I  ---
                                                                                                    REQUEST https://www.rollingstone.com/rss failed with exception: java.lang.IllegalStateException: You must call Bugsnag.start before any other Bugsnag methods
                                                                                                    ---
2024-02-21 16:43:05.402  4938-4938  AndroidRuntime          dev.sasikanth.rss.reader.debug       E  FATAL EXCEPTION: main
                                                                                                    Process: dev.sasikanth.rss.reader.debug, PID: 4938
                                                                                                    java.lang.IllegalStateException: You must call Bugsnag.start before any other Bugsnag methods
                                                                                                    	at com.bugsnag.android.Bugsnag.getClient(Bugsnag.java:480)
                                                                                                    	at com.bugsnag.android.Bugsnag.addMetadata(Bugsnag.java:256)
                                                                                                    	at co.touchlab.crashkios.bugsnag.BugsnagCallsActual.setCustomValue(BugsnagCallsActual.kt:19)
                                                                                                    	at co.touchlab.crashkios.bugsnag.BugsnagKotlin.setCustomValue(BugsnagKotlin.kt:21)
                                                                                                    	at dev.sasikanth.rss.reader.home.HomePresenter$PresenterInstance$addFeed$1.invokeSuspend(HomePresenter.kt:319)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4039a78, Dispatchers.Main]
2024-02-21 16:43:05.415  4938-4938  Process                 dev.sasikanth.rss.reader.debug       I  Sending signal. PID: 4938 SIG: 9
2024-02-21 16:47:14.650  5144-5144  ApplicationLoaders      dev.sasikanth.rss.reader.debug       D  Returning zygote-cached class loader: /system_ext/framework/androidx.window.extensions.jar
2024-02-21 16:47:14.651  5144-5144  ApplicationLoaders      dev.sasikanth.rss.reader.debug       D  Returning zygote-cached class loader: /system_ext/framework/androidx.window.sidecar.jar
2024-02-21 16:47:14.654  5144-5144  ziparchive              dev.sasikanth.rss.reader.debug       W  Unable to open '/data/app/~~4MgPC-gMUXobTdJEBlNTkQ==/dev.sasikanth.rss.reader.debug-dDrj1UkmM2UX4O1QCkQnNA==/base.dm': No such file or directory
2024-02-21 16:47:14.654  5144-5144  ziparchive              dev.sasikanth.rss.reader.debug       W  Unable to open '/data/app/~~4MgPC-gMUXobTdJEBlNTkQ==/dev.sasikanth.rss.reader.debug-dDrj1UkmM2UX4O1QCkQnNA==/base.dm': No such file or directory
2024-02-21 16:47:15.020  5144-5144  nativeloader            dev.sasikanth.rss.reader.debug       D  Configuring clns-6 for other apk /data/app/~~4MgPC-gMUXobTdJEBlNTkQ==/dev.sasikanth.rss.reader.debug-dDrj1UkmM2UX4O1QCkQnNA==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~4MgPC-gMUXobTdJEBlNTkQ==/dev.sasikanth.rss.reader.debug-dDrj1UkmM2UX4O1QCkQnNA==/lib/x86_64:/data/app/~~4MgPC-gMUXobTdJEBlNTkQ==/dev.sasikanth.rss.reader.debug-dDrj1UkmM2UX4O1QCkQnNA==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand:/data/user/0/dev.sasikanth.rss.reader.debug
2024-02-21 16:47:15.030  5144-5144  GraphicsEnvironment     dev.sasikanth.rss.reader.debug       V  Currently set values for:
2024-02-21 16:47:15.030  5144-5144  GraphicsEnvironment     dev.sasikanth.rss.reader.debug       V    angle_gl_driver_selection_pkgs=[]
2024-02-21 16:47:15.031  5144-5144  GraphicsEnvironment     dev.sasikanth.rss.reader.debug       V    angle_gl_driver_selection_values=[]
2024-02-21 16:47:15.031  5144-5144  GraphicsEnvironment     dev.sasikanth.rss.reader.debug       V  ANGLE GameManagerService for dev.sasikanth.rss.reader.debug: false
2024-02-21 16:47:15.032  5144-5144  GraphicsEnvironment     dev.sasikanth.rss.reader.debug       V  dev.sasikanth.rss.reader.debug is not listed in per-application setting
2024-02-21 16:47:15.032  5144-5144  GraphicsEnvironment     dev.sasikanth.rss.reader.debug       V  Neither updatable production driver nor prerelease driver is supported.
2024-02-21 16:47:15.034  5144-5144  ActivityThread          dev.sasikanth.rss.reader.debug       W  Application dev.sasikanth.rss.reader.debug is suspending. Debugger needs to resume to continue.
2024-02-21 16:47:15.035  5144-5144  System.out              dev.sasikanth.rss.reader.debug       I  Sending WAIT chunk
2024-02-21 16:47:15.035  5144-5144  System.out              dev.sasikanth.rss.reader.debug       I  Waiting for debugger first packet
2024-02-21 16:47:15.339  5144-5144  System.out              dev.sasikanth.rss.reader.debug       I  Debug.suspendAllAndSentVmStart
2024-02-21 16:47:15.447  5144-5144  System.out              dev.sasikanth.rss.reader.debug       I  Debug.suspendAllAndSendVmStart, resumed
2024-02-21 16:47:15.770  5144-5144  WM-PackageManagerHelper dev.sasikanth.rss.reader.debug       D  Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService
2024-02-21 16:47:15.770  5144-5144  WM-Schedulers           dev.sasikanth.rss.reader.debug       D  Created SystemJobScheduler and enabled SystemJobService
2024-02-21 16:47:15.806  5144-5168  WM-ForceStopRunnable    dev.sasikanth.rss.reader.debug       D  The default process name was not specified.
2024-02-21 16:47:15.807  5144-5168  WM-ForceStopRunnable    dev.sasikanth.rss.reader.debug       D  Performing cleanup operations.
2024-02-21 16:47:15.852  5144-5168  WM-SystemJobScheduler   dev.sasikanth.rss.reader.debug       D  Reconciling jobs
2024-02-21 16:47:15.863  5144-5168  Compatibil...geReporter dev.sasikanth.rss.reader.debug       D  Compat change id reported: 160794467; UID 10193; state: ENABLED
2024-02-21 16:47:15.866  5144-5168  WM-ForceStopRunnable    dev.sasikanth.rss.reader.debug       D  Found unfinished work, scheduling it.
2024-02-21 16:47:15.893  5144-5168  Compatibil...geReporter dev.sasikanth.rss.reader.debug       D  Compat change id reported: 194532703; UID 10193; state: ENABLED
2024-02-21 16:47:15.893  5144-5168  Compatibil...geReporter dev.sasikanth.rss.reader.debug       D  Compat change id reported: 253665015; UID 10193; state: ENABLED
2024-02-21 16:47:15.894  5144-5168  WM-SystemJobScheduler   dev.sasikanth.rss.reader.debug       D  Scheduling work ID eb42a472-0801-48f2-b9d9-e759455365d5Job ID 2
2024-02-21 16:47:15.901  5144-5168  WM-SystemJobScheduler   dev.sasikanth.rss.reader.debug       D  Scheduling work ID b37bd242-c629-4abd-926a-045452f66ef0Job ID 4
2024-02-21 16:47:16.101  5144-5174  libEGL                  dev.sasikanth.rss.reader.debug       D  loaded /vendor/lib64/egl/libEGL_emulation.so
2024-02-21 16:47:16.107  5144-5174  libEGL                  dev.sasikanth.rss.reader.debug       D  loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
2024-02-21 16:47:16.113  5144-5174  libEGL                  dev.sasikanth.rss.reader.debug       D  loaded /vendor/lib64/egl/libGLESv2_emulation.so
2024-02-21 16:47:16.241  5144-5144  AppCompatDelegate       dev.sasikanth.rss.reader.debug       D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2024-02-21 16:47:16.484  5144-5144  ss.reader.debug         dev.sasikanth.rss.reader.debug       W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2024-02-21 16:47:16.484  5144-5144  ss.reader.debug         dev.sasikanth.rss.reader.debug       W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2024-02-21 16:47:16.499  5144-5144  Compatibil...geReporter dev.sasikanth.rss.reader.debug       D  Compat change id reported: 237531167; UID 10193; state: DISABLED
2024-02-21 16:47:16.502  5144-5144  OpenGLRenderer          dev.sasikanth.rss.reader.debug       W  Unknown dataspace 0
2024-02-21 16:47:16.512  5144-5144  Choreographer           dev.sasikanth.rss.reader.debug       I  Skipped 55 frames!  The application may be doing too much work on its main thread.
2024-02-21 16:47:17.116  5144-5144  ss.reader.debug         dev.sasikanth.rss.reader.debug       W  Method java.lang.Object androidx.compose.runtime.snapshots.SnapshotStateMap.mutate(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
                                                                                                    Common causes for lock verification issues are non-optimized dex code
                                                                                                    and incorrect proguard optimizations.
2024-02-21 16:47:17.117  5144-5144  ss.reader.debug         dev.sasikanth.rss.reader.debug       W  Method void androidx.compose.runtime.snapshots.SnapshotStateMap.update(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
2024-02-21 16:47:17.118  5144-5144  ss.reader.debug         dev.sasikanth.rss.reader.debug       W  Method boolean androidx.compose.runtime.snapshots.SnapshotStateMap.removeIf$runtime_release(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
2024-02-21 16:47:17.524  5144-5144  System.err              dev.sasikanth.rss.reader.debug       W  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2024-02-21 16:47:17.524  5144-5144  System.err              dev.sasikanth.rss.reader.debug       W  SLF4J: Defaulting to no-operation (NOP) logger implementation
2024-02-21 16:47:17.524  5144-5144  System.err              dev.sasikanth.rss.reader.debug       W  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2024-02-21 16:47:18.127  5144-5144  ss.reader.debug         dev.sasikanth.rss.reader.debug       W  Method boolean androidx.compose.runtime.snapshots.SnapshotStateList.conditionalUpdate(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
2024-02-21 16:47:18.127  5144-5144  ss.reader.debug         dev.sasikanth.rss.reader.debug       W  Method java.lang.Object androidx.compose.runtime.snapshots.SnapshotStateList.mutate(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
2024-02-21 16:47:18.127  5144-5144  ss.reader.debug         dev.sasikanth.rss.reader.debug       W  Method void androidx.compose.runtime.snapshots.SnapshotStateList.update(kotlin.jvm.functions.Function1) failed lock verification and will run slower.
2024-02-21 16:47:18.623  5144-5144  Compatibil...geReporter dev.sasikanth.rss.reader.debug       D  Compat change id reported: 171228096; UID 10193; state: ENABLED
2024-02-21 16:47:18.944  5144-5172  OpenGLRenderer          dev.sasikanth.rss.reader.debug       W  Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2024-02-21 16:47:18.945  5144-5172  OpenGLRenderer          dev.sasikanth.rss.reader.debug       W  Failed to initialize 101010-2 format, error = EGL_SUCCESS
2024-02-21 16:47:18.993  5144-5172  Gralloc4                dev.sasikanth.rss.reader.debug       I  mapper 4.x is not supported
2024-02-21 16:47:19.014  5144-5172  OpenGLRenderer          dev.sasikanth.rss.reader.debug       E  Unable to match the desired swap behavior.
2024-02-21 16:47:19.085  5144-5158  OpenGLRenderer          dev.sasikanth.rss.reader.debug       I  Davey! duration=3500ms; Flags=1, FrameTimelineVsyncId=53664, IntendedVsync=742961389722, Vsync=743878056352, InputEventId=0, HandleInputStart=743893981900, AnimationStart=743894010600, PerformTraversalsStart=743894356700, DrawStart=746396093300, FrameDeadline=742978056388, FrameInterval=743893363200, FrameStartTime=16666666, SyncQueued=746426566000, SyncStart=746427179700, IssueDrawCommandsStart=746428287400, SwapBuffers=746453011300, FrameCompleted=746462552300, DequeueBufferDuration=23200, QueueBufferDuration=228500, GpuCompleted=746462552300, SwapBuffersCompleted=746454093400, DisplayPresentTime=0, CommandSubmissionCompleted=746453011300, 
2024-02-21 16:47:19.120  5144-5144  Choreographer           dev.sasikanth.rss.reader.debug       I  Skipped 142 frames!  The application may be doing too much work on its main thread.
2024-02-21 16:47:19.203  5144-5161  OpenGLRenderer          dev.sasikanth.rss.reader.debug       I  Davey! duration=2451ms; Flags=0, FrameTimelineVsyncId=53769, IntendedVsync=744128056342, Vsync=746494722914, InputEventId=0, HandleInputStart=746501495600, AnimationStart=746501538500, PerformTraversalsStart=746565947500, DrawStart=746566167500, FrameDeadline=746494722914, FrameInterval=746500460300, FrameStartTime=16666666, SyncQueued=746572213600, SyncStart=746572479900, IssueDrawCommandsStart=746572596000, SwapBuffers=746573179900, FrameCompleted=746579514200, DequeueBufferDuration=22200, QueueBufferDuration=264900, GpuCompleted=746579514200, SwapBuffersCompleted=746574452100, DisplayPresentTime=0, CommandSubmissionCompleted=746573179900, 
2024-02-21 16:47:21.761  5144-5193  ProfileInstaller        dev.sasikanth.rss.reader.debug       D  Installing profile for dev.sasikanth.rss.reader.debug
2024-02-21 16:47:46.181  5144-5172  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=1805.92ms min=3.88ms max=26357.35ms count=15
2024-02-21 16:47:48.002  5144-5172  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=904.51ms min=8.06ms max=1800.96ms count=2
2024-02-21 16:47:48.474  5144-5144  Compatibil...geReporter dev.sasikanth.rss.reader.debug       D  Compat change id reported: 289878283; UID 10193; state: ENABLED
2024-02-21 16:47:49.011  5144-5172  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=112.01ms min=54.61ms max=403.65ms count=9
2024-02-21 16:48:10.783  5144-5172  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=10884.13ms min=3.73ms max=21764.54ms count=2
2024-02-21 16:48:10.973  5144-5144  WindowOnBackDispatcher  dev.sasikanth.rss.reader.debug       W  sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@d8699
2024-02-21 16:48:12.513  5144-5172  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=143.43ms min=4.98ms max=1078.26ms count=12
2024-02-21 16:48:23.015  5144-5172  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=874.70ms min=5.21ms max=9829.44ms count=12
2024-02-21 16:48:23.205  5144-5144  WindowOnBackDispatcher  dev.sasikanth.rss.reader.debug       W  sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@d8699
2024-02-21 16:48:24.676  5144-5172  EGL_emulation           dev.sasikanth.rss.reader.debug       D  app_time_stats: avg=110.00ms min=4.38ms max=1025.98ms count=15
2024-02-21 16:50:32.011  5144-5150  ss.reader.debug         dev.sasikanth.rss.reader.debug       I  Thread[4,tid=5150,WaitingInMainSignalCatcherLoop,Thread*=0x751a351dbf50,peer=0x13a00000,"Signal Catcher"]: reacting to signal 3
2024-02-21 16:50:32.011  5144-5150  ss.reader.debug         dev.sasikanth.rss.reader.debug       I  
2024-02-21 16:50:32.292  5144-5150  ss.reader.debug         dev.sasikanth.rss.reader.debug       I  Wrote stack traces to tombstoned
2024-02-21 16:50:39.530  5144-5161  ss.reader.debug         dev.sasikanth.rss.reader.debug       I  Explicit concurrent copying GC freed 63501(2486KB) AllocSpace objects, 3(60KB) LOS objects, 49% free, 7264KB/14MB, paused 472us,67us total 75.294ms
```

**Comment by msasikanth** [comment]
It's not related to code, it seems to be an env issue as I can load the given feeds without any issues.

**Comment by tejuguasu** [comment]
Apparently, without changing more things in the code, you need to update `androidApp/src/androidMain/kotlin/dev/sasikanth/rss/reader/ReaderApplication.kt` to call `Bugsnag.start` in any case (either using the environment variable `BUGSNAG_API_KEY` or passing one as an argument). The API key doesn't need to be a valid one. Without that, the application fails to add a new feed.

```Kotlin
    if (!BuildConfig.DEBUG) {
      Bugsnag.start(this)
    }
    else {
      Bugsnag.start(this, "dummy")
    }
    enableBugsnag()
```
&nbsp;
I want to store the `key=value` pairs in the project folder and `local.properties` seems a good place.
For those values to be picked up by Gradle for Android, I used [i30mb1](https://stackoverflow.com/users/9674249/i30mb1) answer to [this StackOverflow question](https://stackoverflow.com/questions/60474010/read-value-from-local-properties-via-kotlin-dsl) so added the following to `androidApp/build.gradle.kts`

```Kotlin
import java.util.Properties

// Define a function to load the local properties
fun loadLocalProperties(project: Project): Properties {
  val localProperties = Properties()
  val localPropertiesFile = project.rootProject.file("local.properties")
  if (localPropertiesFile.exists()) {
    localProperties.load(localPropertiesFile.inputStream())
  }
  return localProperties
}
val localProperties = loadLocalProperties(project)
```
&nbsp;
and finally, updated the way the manifest placeholder is assigned

```Kotlin
val keyBugsnagAPIKey = "BUGSNAG_API_KEY"
    val bugsnagApiKey = System.getenv(keyBugsnagAPIKey).takeUnless { it.isNullOrEmpty() }
      ?: localProperties.getProperty(keyBugsnagAPIKey, "")
    manifestPlaceholders[keyBugsnagAPIKey] = bugsnagApiKey
```
&nbsp;
I hope this helps others who are new to the language and frameworks.

**Comment by msasikanth** [comment]
> Apparently, without changing more things in the code, you need to update `androidApp/src/androidMain/kotlin/dev/sasikanth/rss/reader/ReaderApplication.kt` to call `Bugsnag.start` in any case (either using the environment variable `BUGSNAG_API_KEY` or passing one as an argument). The API key doesn't need to be a valid one. Without that, the application fails to add a new feed.
> 
> 
> 
> ```Kotlin
> 
>     if (!BuildConfig.DEBUG) {
> 
>       Bugsnag.start(this)
> 
>     }
> 
>     else {
> 
>       Bugsnag.start(this, "dummy")
> 
>     }
> 
>     enableBugsnag()
> 
> ```
> 
> &nbsp;
> 
> I want to store the `key=value` pairs in the project folder and `local.properties` seems a good place.
> 
> For those values to be picked up by Gradle for Android, I used [i30mb1](https://stackoverflow.com/users/9674249/i30mb1) answer to [this StackOverflow question](https://stackoverflow.com/questions/60474010/read-value-from-local-properties-via-kotlin-dsl) so added the following to `androidApp/build.gradle.kts`
> 
> 
> 
> ```Kotlin
> 
> import java.util.Properties
> 
> 
> 
> // Define a function to load the local properties
> 
> fun loadLocalProperties(project: Project): Properties {
> 
>   val localProperties = Properties()
> 
>   val localPropertiesFile = project.rootProject.file("local.properties")
> 
>   if (localPropertiesFile.exists()) {
> 
>     localProperties.load(localPropertiesFile.inputStream())
> 
>   }
> 
>   return localProperties
> 
> }
> 
> val localProperties = loadLocalProperties(project)
> 
> ```
> 
> &nbsp;
> 
> and finally, updated the way the manifest placeholder is assigned
> 
> 
> 
> ```Kotlin
> 
> val keyBugsnagAPIKey = "BUGSNAG_API_KEY"
> 
>     val bugsnagApiKey = System.getenv(keyBugsnagAPIKey).takeUnless { it.isNullOrEmpty() }
> 
>       ?: localProperties.getProperty(keyBugsnagAPIKey, "")
> 
>     manifestPlaceholders[keyBugsnagAPIKey] = bugsnagApiKey
> 
> ```
> 
> &nbsp;
> 
> I hope this helps others who are new to the language and frameworks.

That's not needed. I made changes to the code that just skips the BugSnag log writer in debug builds. 

https://github.com/msasikanth/twine/blob/4b378014707ec0073a8dfc3ff88930ca65a17527/shared/src/commonMain/kotlin/dev/sasikanth/rss/reader/logging/LoggingInitializer.kt#L35

**Comment by tejuguasu** [comment]
> That's not needed. I made changes to the code that just skips the BugSnag log writer in debug builds.

Well, all I can say is that in my case, cloning the repository and debugging the app without other changes than setting the Android SDK path, failed until I added the bugsnag key.
