### ISSUE TITLE
KeyError: 'home-page' raised when trying to use twine 5.1.0 with importlib-metadata 8.0.0

### ISSUE THREAD

**Issue by fabioz** [msasikanth/twine#624]
**Describe the bug**

With:
```
Collecting importlib-metadata>=3.6 (from twine)
  Downloading importlib_metadata-8.0.0-py3-none-any.whl.metadata (4.6 kB)
```

I get the error below

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/bin/twine", line 5, in <module>
    from twine.__main__ import main
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/twine/__init__.py", line 40, in <module>
    __uri__ = metadata["home-page"]
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'home-page'
```

-- whereas it did previously work with:

```
Collecting importlib-metadata>=3.6 (from twine)
  Downloading importlib_metadata-7.2.0-py3-none-any.whl.metadata (4.7 kB)
```

**To Reproduce**
1. Create a project with poetry without setting the `homepage` (which is optional) and try to use twine to do the upload and it should raise this error.

**Stacktrace**
If present, add stacktrace to help debug the issue faster.

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/bin/twine", line 5, in <module>
    from twine.__main__ import main
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/twine/__init__.py", line 40, in <module>
    __uri__ = metadata["home-page"]
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'home-page'
```

The commit that broke it is probably: https://github.com/python/importlib_metadata/commit/a970a491b56a3bf529821ce21867af4573cf2e0d

**Comment by msasikanth** [comment]
This is an Android and iOS RSS reader app. I think you got the wrong repo

**Comment by fabioz** [comment]
Oops, sorry, wrong twine.
